source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails', '4.0.0'

gem 'actionpack-action_caching'
gem 'actionpack-page_caching'
gem 'active_model_serializers'
gem 'addressable'
gem 'aws-sdk'
gem 's3_direct_upload'
gem 'bullet', :group => :development
gem 'canable'
gem 'carrierwave'
gem 'coffee-rails'
gem "compass-rails", "~> 2.0.alpha.0"
gem 'dalli'
gem 'dotenv-rails'
gem 'fog'
gem 'gravatar_image_tag'
gem 'haml'
gem 'ims-lti'
gem 'jbuilder'
gem 'jquery-rails', '~> 2.0'
gem 'jquery.fileupload-rails'
gem 'json'
gem 'kiqstand', :git => 'https://github.com/mongoid/kiqstand.git'
gem 'markerb'
gem 'mini_magick'
gem 'minitest-rails'
gem 'mongoid', :git => 'https://github.com/mongoid/mongoid.git'
gem 'newrelic_rpm'
gem 'nokogiri', '1.6.0'
gem 'oink'
gem 'omniauth'
gem 'omniauth-kerberos'
gem 'omniauth-lti'
gem 'pacecar'
gem 'pg'
gem 'protected_attributes'
gem 'puma'
gem 'quiet_assets', :group => :development
gem 'rails_autolink'
gem 'rdiscount'
gem 'responders'
gem 'rollbar'
gem 'sampler'
gem 'sanitize'
gem 'sass-rails', '~> 4.0.0.beta1'
gem 'sendgrid'
gem 'sidekiq'
gem 'simple_calendar', '~> 0.1.9'
gem 'simple_form', '~> 3.0.0.rc'
gem 'sorcery'
gem 'timelineJS-rails'
gem 'uglifier'
gem 'whenever'
gem 'will_paginate', '~> 3.0'
gem 'foundation-rails'

group :development do
  gem 'guard'
  gem 'guard-minitest'
  gem 'haml-rails'
  gem 'minitest-colorize'
  gem 'minitest-matchers'
  gem 'minitest-reporters'
  gem 'minitest-capybara'
  gem 'valid_attribute'
  gem 'capybara'
  gem 'foreman'
  gem 'rubystats'
end

group :test do
  gem 'faker'
end

group :test, :development do
  gem 'debugger'
  gem 'fabrication'
  gem 'capybara-webkit'
  gem 'capybara-screenshot'
  gem 'launchy'
  gem 'database_cleaner'
end
