source 'https://rubygems.org'

ruby '2.0.0'
gem 'rails', '4.0.0'

gem 'actionpack-action_caching'
gem 'actionpack-page_caching'
gem 'active_model_serializers'
gem 'airbrake'
gem 'canable'
gem 'carrierwave'
gem 'coffee-rails'
gem 'compass-rails', :git => 'https://github.com/milgner/compass-rails', :branch => 'rails4'
gem 'dalli'
gem 'dotenv-rails'
gem 'gravatar_image_tag'
gem 'haml'
gem 'ims-lti'
gem 'jbuilder'
gem 'jquery-rails', '~> 2.0'
gem 'jquery.fileupload-rails'
gem 'json'
gem 'markerb'
gem 'minitest-rails'
gem 'newrelic_rpm'
gem 'nokogiri', '1.6.0'
gem 'omniauth'
gem 'omniauth-lti'
gem 'pacecar'
gem 'pg'
gem 'protected_attributes'
gem 'puma'
gem 'quiet_assets', :group => :development
gem 'rdiscount'
gem 'rails_12factor'
gem 'rails_autolink'
gem 'responders'
gem 'sampler'
gem 'sanitize'
gem 'sass-rails', '~> 4.0.0.beta1'
gem 'sendgrid'
gem 'simple_calendar', '~> 0.1.9'
gem 'simple_form', '~> 3.0.0.rc'
gem 'sorcery'
gem 'timelineJS-rails'
gem 'uglifier'
gem 'whenever'

group :development do
  gem 'bullet'
  gem 'guard'
  gem 'guard-minitest'
  gem 'haml-rails'
  gem 'minitest-colorize'
  gem 'minitest-matchers'
  gem 'minitest-reporters'
  gem 'minitest-capybara'
  gem 'valid_attribute'
  gem 'capybara'
end

group :test do
  gem 'faker'
end

group :test, :development do
  gem 'debugger'
  gem 'fabrication'
  gem 'capybara-webkit'
  gem 'capybara-screenshot'
  gem 'launchy'
  gem 'database_cleaner'
end
